### ISSUE TITLE
ERROR Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by rafaelribeiroo** [carmolim/olx-monitor#15]
Boa tarde amigo,

Acredito que a OLX passou por uma nova estruturação de dados, poderia por gentileza atualizar o código para que se adeque às novas alterações? Funcionava perfeitamente durante todo o mês, mas hoje está resultando no erro mostrado no print abaixo.

![image](https://github.com/carmolim/olx-monitor/assets/19275140/63986882-8a20-4716-9ce5-6c789ce81617)

**Comment by carmolim** [comment]
Antes, tenta fazer um teste removendo o `o=4758` no final da sua URL para ver se funciona por favor.

**Comment by rafaelribeiroo** [comment]
Claro, pra já, eu havia mantido apenas uma URL sem nenhuma query string adicional se não o produto desejado, porém segue retornando erro, só que dessa vez BAD REQUEST (400), segue abaixo o log para análises.

![image](https://github.com/carmolim/olx-monitor/assets/19275140/11b62373-d806-4cdf-9350-8cc4639b3c50)
![image](https://github.com/carmolim/olx-monitor/assets/19275140/13503a01-eee1-4acf-9331-2a62d60e2594)

**Comment by rafaelribeiroo** [comment]
Desculpe, agora foi um erro meu, eu transformei o grupo em super grupo e o id passou por uma mudança, fiz a atualização e passei a receber os updates normalmente, alguma vez você já pegou casos em que a notificação vinha sem o link?

**Comment by carmolim** [comment]
Tranquilo @rafaelribeiroo, não lembro de ter tido esse problema da notificação não mandar o link, que informações você recebeu nessas notificações que estavam sem o link?

**Comment by rafaelribeiroo** [comment]
Oba, não é algo corriqueiro, porém quando ocorre é bem desagradável pro usuário, se quiser eu te envio os logs, mas fica dessa forma (evidências abaixo)

![image](https://github.com/carmolim/olx-monitor/assets/19275140/1a361059-6555-424e-b16c-398cd88a4aff)
![image](https://github.com/carmolim/olx-monitor/assets/19275140/58b4a54a-f448-4d27-b33a-90b949a0f2ed)

**Comment by carmolim** [comment]
@rafaelribeiroo sabe dizer se a falha no envio dos links acontece também com o código original? Parece que você fez algumas alterações pelo menos no padrão das mensagens. SE tiver acontecendo também com o código original vai ser mais simples de debugar.

**Comment by rafaelribeiroo** [comment]
Debugei e solucionei amigo, obrigado
