### ISSUE TITLE
Problemas em encontrar novos anúncios

### ISSUE THREAD

**Issue by mermao1** [carmolim/olx-monitor#17]
Alguém percebeu se houve uma baixa de notificações após o último commit?

Eu estava utilizando o commit 1af2f03 há algumas semanas e o script estava funcionando bem, encontrando novos anúncios que correspondiam aos meus filtros, e me notificando no Telegram. Eu sou o inimigo do update quando algo está funcionando, então mesmo após a última atualização 6aaa31c, eu permaneci no commit anterior 1af2f03.

Eis que há uma semana atrás, eu estava ocioso e atualizei para o último commit.
O script rodou ok, e continuou me notificando sobre baixa de preços dos anúncios que eu já tinha em DB, mas após alguns dias eu percebi que houve uma baixa nas notificações de novos anúncios, e até pensei: "Devem ser as pessoas que estão vendendo menos esse mês" 😂
Se antes eu recebia umas 3-5 notificações de novos anúncios por dia, após a atualização eu passei alguns dias sem receber nenhuma notificação de novos anúncios, mas apenas notificação de preços caindo (do que já estava em minha DB).

Acontece que hoje, um amigo me mandou um link de um produto que ele sabia que eu estava esperando aparecer, e o produto correspondia ao filtro que eu havia setado na config, então eu pesquisei no DB e vi que o anúncio não estava no DB.

Para fazer um teste, eu copiei o link de busca do produto diretamente da minha config e colei no navegador, para verificar se o anúncio que meu amigo me passou seria listado no site da OLX.
Quando colei o link de pesquisa no navegador, o anúncio que ele havia me passado apareceu como um dos primeiros resultados, então concluí que o script poderia não estar encontrando ou não estar cadastrando os novos anúncios no DB.

Para tentar voltar ao estado de quando estava funcionando, eu voltei ao commit anterior (git reset 1af2f03 --hard), rodei o script novamente, e esse foi o resultado:
```
10:20:02.330 INFO  Ad 124xxxxx1 added to the database
10:20:02.333 INFO  Ad 124xxxxx8 added to the database
10:20:02.335 INFO  Ad 124xxxxx8 added to the database
10:20:02.576 ERROR SQLITE_CONSTRAINT: UNIQUE constraint failed: ads.id
{"errno":19,"code":"SQLITE_CONSTRAINT"}
Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: ads.id
10:20:02.576 INFO  Ad 124xxxxx6 added to the database
10:20:02.579 INFO  Ad 124xxxxx8 added to the database
10:20:02.581 INFO  Ad 124xxxxx1 added to the database
10:20:02.582 INFO  Ad 124xxxxx4 added to the database
10:20:02.584 INFO  Ad 124xxxxx9 added to the database
10:20:02.586 INFO  Ad 124xxxxx5 added to the database
10:20:02.588 INFO  Ad 124xxxxx2 added to the database
10:20:02.590 INFO  Ad 124xxxxx7 added to the database
10:20:02.591 ERROR SQLITE_CONSTRAINT: UNIQUE constraint failed: ads.id
{"errno":19,"code":"SQLITE_CONSTRAINT"}
Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: ads.id
10:20:02.602 ERROR SQLITE_CONSTRAINT: UNIQUE constraint failed: ads.id
{"errno":19,"code":"SQLITE_CONSTRAINT"}
Error: SQLITE_CONSTRAINT: UNIQUE constraint failed: ads.id
10:20:02.603 INFO  Ad 124xxxxx4 added to the database
10:20:02.813 INFO  Ad 124xxxxx3 added to the database
10:20:02.816 INFO  Ad 110xxxxx1 added to the database
10:20:02.848 INFO  Ad 124xxxxx2 added to the database
10:20:02.850 INFO  Ad 124xxxxx9 added to the database
10:20:02.852 INFO  Ad 124xxxxx6 added to the database
10:20:02.854 INFO  Ad 124xxxxx3 added to the database
10:20:02.856 INFO  Ad 124xxxxx2 added to the database
10:20:02.858 INFO  Ad 124xxxxx9 added to the database
```
(Editei o número dos anúncios com xxxxx).

Quando voltei para o commit antigo (sem deletar a DB) e rodei o script novamente, ele já encontrou diversos novos anúncios que não havia encontrado quando estava no último commit, inclusive o anúncio que meu amigo me mandou o link.
Recebi aproximadamente 20 notificações no Telegram de novos anúncios, acredito que foram os anúncios que eu não recebia enquanto estava no último commit.

Não sei exatamente o que pode ter causado isso, se foi culpa minha, mas apenas reportando para ver se mais alguém teve o mesmo problema.

**Comment by mermao1** [comment]
Realmente eu não lembro se apaguei a db antiga após atualizar para o último commit. Procurei aqui no .bash_history e após o git pull eu entrei direto na minha sessão de screen onde roda o script, e pode ser que eu não tenha apagado mesmo.

Vou fazer backup do db, atualizar o script, apagar o db do diretório e rodar novamente para observar por uns 2-3 dias o povoamento de novos anúncios.

Obrigado pela atenção, @carmolim!

**Comment by mermao1** [comment]
Passando para dar um feedback, @carmolim.
Apaguei o DB, atualizei o script para o último commit e rodei para recriar a DB do zero. Está tudo funcionando perfeitamente, encontrando novos anúncios e notificando no telegram. 
Foi falta de atenção minha, atualizei mantendo o DB antigo. Mal aí e obrigado pela atenção! 💯

**Comment by carmolim** [comment]
Bom saber que está tudo certo @mermao1! 

Nas próximas vezes vou deixar a mensagem de commit mais clara quando tiver uma breaking change, acho isso poderia evitar a situação que aconteceu.
