### ISSUE TITLE
Como contribuir?

### ISSUE THREAD

**Issue by carlosapenasdev** [carmolim/olx-monitor#24]
Adicionei uma funcionalidade que senti falta: filtro por título.
Não consigo construir a PR. Qual branch é a mais atualizada, acredito que seja a docker, mas a branch main é incompatível com ela, como posso propor essa feature, na branch docker mesmo?

**Comment by carmolim** [comment]
Obrigado @carlosapenasdev estive meio sem tempo ultimamente e não consegui terminar de organizar as branchs vou ver se organizo isso no fds para você poder mandar a PR. Obrigado pela contribuição!!

**Comment by carmolim** [comment]
Boa tarde @carlosapenasdev acabei de atualizar a branch main com as últimas modificações que fiz na branch docker, agora vai ficar mais fácil para você enviar a sua contribuição.
