### ISSUE TITLE
Erro ao executar o node index.js

### ISSUE THREAD

**Issue by CarlosRafaelDuarte** [carmolim/olx-monitor#4]
Fiz todos os passos conforme a descrição, porém, não funcionou.
 na hora de rodar o node index.js aparece o seguinte erro como o print abaixo:

![image](https://user-images.githubusercontent.com/78601219/226154364-ca101677-b358-406b-96e7-909de3661191.png)

Instalei o node e fiz o processo pelo npm install tudo certinho,
 estou utilizando uma máquina virtual com o Ubuntu 

 - Se puder me ajudar, serei muito grato !
 -   Esse monitor da OLX é algo fantástico, queria tanto fazer funcionar. Fico no seu aguardo.

**Comment by carmolim** [comment]
o @guipfi sugeriu uma correção em outro issue https://github.com/carmolim/olx-monitor/issues/3 acredito que irá solucionar o seu problema.
