### ISSUE TITLE
Dúvida sobre arquivo .env

### ISSUE THREAD

**Issue by CarlosRafaelDuarte** [carmolim/olx-monitor#5]
Fale amigo, tava revisitando sua aplicação e fiz todos os passos.
 porém na hora de ler os parâmetros do BOT não consegui

 o erro é esse aqui

![image](https://user-images.githubusercontent.com/78601219/235309770-535281c1-8da1-4c4c-8b17-403e62f9fe64.png)

Serei muito grato se conseguir me ajudar, to precisando muito monitorar os preços da OLX.

**Comment by carmolim** [comment]
Pela mensagem de erro parece que o dotenv não está instalado, tente rodar novamente o comando

```
npm i

// ou instale apenas o .env 

npm install dotenv

```

**Comment by CarlosRafaelDuarte** [comment]
> Pela mensagem de erro parece que o dotenv não está instalado, tente rodar novamente o comando
> 
> ```shell
> npm i
> 
> // ou instale apenas o dotenv
> 
> npm install dotenv
> ```

Fale meu amigo, em primeiro lugar, parabéns pela sua humildade em ajudar.
 Fiz o que você disse e deu certo.
 
  A aplicação funcionou e armazenou as informações no banco de dados, só tem mais uma coisa...
   Não está enviando mensagem para o telegram , o BOT está tudo OK pois já testei... Inclusive através do auxílio do ChatGPT conseguir fazer um script em Pyhton que ele lê as consultas salvas no banco de dados e envia para o Telegram.
   
    Porém, queria muito saber o que deu errado no código que não funcionou o telegram, vou te mandar um print de como está as confg.
    
    Esse abaixo é o arquivo .env
    
![image](https://user-images.githubusercontent.com/78601219/235513503-ed1d0ef2-aa14-4512-a280-7408be5805cb.png)


Arquivos da pasta
![image](https://user-images.githubusercontent.com/78601219/235513654-5da651e9-91cc-4b49-84ec-acce1f8f73c5.png)


E o log com o item que estava testando a busca
![image](https://user-images.githubusercontent.com/78601219/235513929-38a11e0a-cc41-43d2-9f10-53a76691e8bb.png)

 Se puder me ajudar mais com essa, serei muito grato !! ;)

**Comment by carmolim** [comment]
Que bom que funcionou! Aparentemente está tudo certo mesmo, o que pode estar acontecendo é que na primeira vez que o script é executado ele não envia nenhuma notificação para o telegram, porque senão ele mandaria uma notificação para cada um dos anúncios e dependendo da pesquisa que você estiver fazendo pode acabar gerando muitas mensagens e o telegram vai parar de enviar as mensagens por um período de tempo. 

Então só são enviadas mensagens quando aparece um novo anúncio oi se um anúncio existente tiver uma mudança de preço. 

Acredito que seja isso que está acontecendo, tente deixar rodando por alguns dias para ver se aparece recebe alguma notificação ou se aparece algum erro nos logs.

**Comment by carmolim** [comment]
@CarlosRafaelDuarte fiz alguns testes com a versão que você estava rodando e ela só estava enviando notificações quando uma baixa no preço fosse detectada, mas não enviava uma notificação quando um novo item era encontrado, enviei uma correção agora para esse problema: https://github.com/carmolim/olx-monitor/pull/7

**Comment by CarlosRafaelDuarte** [comment]
@carmolim muito obrigado pelo retorno, fiz o upgrade aqui pra sua versão, ficou muito show!! Parabéns!
