### ISSUE TITLE
Error: SQLITE_CONSTRAINT: NOT NULL constraint failed: ads.searchTerm

### ISSUE THREAD

**Issue by pedroatmc** [carmolim/olx-monitor#6]
Acontece quando eu inicializo o index.js
Segue o arquivo de configuração:

```
require('dotenv').config()

let config = {}

config.urls = [
    'https://www.olx.com.br/videogames/estado-pe/grande-recife?vgm=18&vgm=17',
    'https://www.olx.com.br/videogames?op=2&vgm=18&vgm=17&opst=2'
]

// this tool can help you create the interval string:
// https://tool.crontap.com/cronjob-debugger

config.interval = '*/5 * * * *' 
config.telegramChatID = process.env.TELEGRAM_CHAT_ID
config.telegramToken = process.env.TELEGRAM_TOKEN
config.logFile = 'scrapper.log'
config.dbFile = 'ads.db'

module.exports = config
```

O token foi configurado de acordo com o Token entregue pelo @botfather no formato: 1234567890:AAAAAAAAAAAAAAAAAA
O bot foi adicionado ao grupo, cujo ID foi obtido pelo IDBot no formato:  -123456789

**Comment by carmolim** [comment]
Acredito que você encontrou um BUG, o que está acontecendo é que na URL que você colocou no config não tem um termo de busca, apenas categorias selecionadas e o script espera que tenha algum termo de pesquisa, tente incluir a seguinte URL:

`https://www.olx.com.br/videogames?q=nintendo%20switch&op=2&vgm=18&vgm=17&opst=2`

Acredito que assim irá funcionar, qualquer coisa pode reabrir o ticket.
